// resources/js/app/pages/tracker/media.tsx
import { useParams } from 'react-router'
import { useEffect, useState } from 'react'
import { Button, Card, Col, FormSelect, Row } from 'react-bootstrap'
import clsx from 'clsx'
import { orderBy } from 'lodash'

import { PageDescription, PageTitle } from '@metronic'
import { Preloader, TorrentCard, Icon, EmptyState } from '@/components'
import { confirm, notifySuccess } from '@/helpers'
import { ITorrent, useApi } from '@/api'
import { useDispatch, useSelector } from '@/store'
import { loadMedia, selectError, selectIsLoadingMedia, selectMedia } from '@/store/media'

const useSort = () => {
  const [sortBy, setSortBy] = useState('size_int')
  const [sortingOrder, setSortingOrder] = useState<'asc' | 'desc'>('desc')

  const switchSortingOrder = () => setSortingOrder(sortingOrder === 'asc' ? 'desc' : 'asc')
  const sortingOrderIcon = sortingOrder === 'asc' ? 'sort-amount-down-alt' : 'sort-amount-down'

  return {
    sortBy,
    setSortBy,
    switchSortingOrder,
    sortingOrderIcon,
    sortingOrder,
  }
}

const TrackerMediaPage = () => {
  const api = useApi()
  const dispatch = useDispatch()

  const { mediaId } = useParams()

  const isLoading = useSelector(selectIsLoadingMedia)
  const media = useSelector(selectMedia)
  const error = useSelector(selectError)

  useEffect(() => {
    if (mediaId && mediaId !== media?.id) {
      dispatch(loadMedia(mediaId))
    }
  }, [])

  const { switchSortingOrder, sortBy, setSortBy, sortingOrder, sortingOrderIcon } = useSort()
  const isSomeSeriesTorrents = media ? media.torrents.some((torrent) => torrent.content_type === 'series') : false
  const [isTogglingFavorite, setTogglingFavorite] = useState(false)

  if (isLoading) {
    return (
      <>
        <PageTitle>Загрузка...</PageTitle>
        <Preloader />
      </>
    )
  }

  if (error) {
    const sentryLink = 'https://sentry.io/organizations/personal-purposes/issues/?project=5284009'

    return (
      <>
        <PageTitle>Ошибка</PageTitle>
        <EmptyState variant="danger" icon="exclamation-triangle">
          Произошла ошибка. Подробности в <strong><a href={sentryLink}>Sentry</a></strong>
        </EmptyState>
      </>
    )
  }

  if (!media) {
    return (
      <>
        <PageTitle>Ошибка</PageTitle>
        <div className="d-flex justify-content-center">
          Медиа контент не найден
        </div>
      </>
    )
  }

  const sortedTorrents = (() => {
    if (sortBy === 'size_int') {
      return orderBy(media.torrents, ['size_int'], [sortingOrder])
    }

    if (sortBy === 'season') {
      return orderBy(media.torrents, ['season', 0], [sortingOrder])
    }

    return media.torrents
  })()

  const openMediaPageInTracker = () => {
    window.open(media.url)
  }

  const toggleFavorite = async () => {
    try {
      setTogglingFavorite(true)
      if (media.is_favorite) {
        await api.removeFromFavorites(media.id)
        media.is_favorite = false
      } else {
        await api.addToFavorites(media.id)
        media.is_favorite = true
      }
    } finally {
      setTogglingFavorite(false)
    }
  }

  const handleDownload = async (torrent: ITorrent) => {
    if (await confirm('Скачать?', torrent.name)) {
      await api.startDownload(torrent.id)
      notifySuccess(torrent.name, 'Загрузка началась')
    }
  }

  return (
    <>
      <PageTitle>{media.title}</PageTitle>
      {media.original_title && (
        <PageDescription>{media.original_title}</PageDescription>
      )}
      <Row>
        <Col md={4} className="mb-4">
          <div className="card ribbon ribbon-start mb-4">
            {media.series_count && (
              <div className="ribbon-label bg-danger" style={{ top: '24px' }}>
                {media.series_count}
              </div>
            )}
            <Card.Img src={media.poster} className="w-100" />
          </div>
          <div className="d-flex gap-2">
            <Button
              size="lg"
              variant={media.is_favorite ? 'warning' : 'info'}
              className={clsx('w-100 btn-icon', isTogglingFavorite && 'spinner spinner-white spinner-right')}
              disabled={isTogglingFavorite}
              onClick={toggleFavorite}
            >
              <Icon name="star" size="2" style={media.is_favorite ? 'solid' : 'light'} />
            </Button>
            <Button
              size="lg"
              variant="info"
              className="w-100 btn-icon"
              onClick={openMediaPageInTracker}
            >
              <Icon name="external-link-square" size="2" />
            </Button>
          </div>
        </Col>
        <Col md={8}>
          <div className="input-group mb-4">
            <FormSelect value={sortBy} onChange={(e) => setSortBy(e.target.value)}>
              <option value="size_int">По размеру</option>
              {isSomeSeriesTorrents && (
                <option value="season">По сезону</option>
              )}
            </FormSelect>
            <div className="input-group-append">
              <Button onClick={switchSortingOrder} className="btn-icon">
                <Icon name={sortingOrderIcon} size="2" />
              </Button>
            </div>
          </div>
          {sortedTorrents.map((torrent) => (
            <div key={torrent.id} className="mb-3">
              <TorrentCard value={torrent} onClick={() => handleDownload(torrent)} />
            </div>
          ))}
        </Col>
      </Row>
    </>
  )
}

export default TrackerMediaPage

// resources/vue/view/pages/Media.vue
<template>
  <div>

    <div v-if="isLoading || media === null" class="d-flex justify-content-center" style="height: 400px;">
      <div v-if="isLoading" class="spinner spinner-track spinner-primary spinner-lg" style="margin-left: -1rem;"></div>
      <p v-else-if="media === null" class="text-center">Медиа контент не найден</p>
    </div>

    <div v-else>
      <MediaSubheader :title="media.title" :subtitle="media.original_title" />
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-4">
            <div class="card ribbon ribbon-clip ribbon-left mb-4">
              <div v-if="media.series_count" class="ribbon-target" style="top: 12px;">
                <span class="ribbon-inner bg-danger"></span>{{ media.series_count }}
              </div>
              <img :src="media.poster" class="card-img-top card-img-bottom" style="width: 100%;">
            </div>
            <div class="btn btn-lg w-100" :class="{ [favoriteButtonClass]: true }" @click="toggleFavorite">В избранное</div>
          </div>
          <div class="col-md-8">
            <div class="input-group mb-4">
              <b-form-select
                v-model="sortBy"
                :options="isSomeSeriesTorrents
                  ? [{ value: 'season', text: 'По сезону'}, { value: 'size_int', text: 'По размеру'}]
                  : [{ value: 'size_int', text: 'По размеру'}]
                "
              />
              <div class="input-group-append">
                <button class="btn btn-primary" type="button" @click="switchSortingOrder">
                  <i class="fa" :class="{ [sortingOrderIcon]: true }"></i>
                </button>
              </div>
            </div>
            <div v-for="torrent in sortedTorrents" class="mb-3">
              <Torrent :torrent="torrent" @download="handleDownload(torrent)" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import MediaSubheader from "./MediaSubheader";
  import Torrent from './Torrent';
  import { loadMedia, loadMediaBlocked, startDownload } from "@/api";
  import notifyMixin from '@/mixins/notifyMixin';
  import asideToggleMixin from '@/mixins/asideToggleMixin';
  import { addToFavorites, removeFromFavorites } from "../../api";

  export default {
    name: "Media",
    mixins: [notifyMixin, asideToggleMixin],
    components: {
      MediaSubheader,
      Torrent,
    },
    data() {
      return {
        isLoading: false,
        media: null,
        sortBy: 'size_int',
        sortingOrder: 'desc',
        isAsideHidden: false,
      }
    },
    computed: {
      tracker() {
        let trackerId = this.$route.params.trackerId;
        return this.$store.getters.trackers.find(tracker => tracker.id === trackerId);
      },
      isSomeSeriesTorrents() {
        return this.media.torrents.some(torrent => torrent.content_type === 'series');
      },
      sortingOrderIcon() {
        return this.sortingOrder === 'asc' ? 'fa-sort-amount-down-alt' : 'fa-sort-amount-down';
      },
      sortedTorrents() {
        if (this.sortBy === 'size_int') {
          return this.$lodash.orderBy(this.media.torrents, ['size_int'], [this.sortingOrder]);
        }

        if (this.sortBy === 'season') {
          return this.$lodash.orderBy(this.media.torrents, ['season', 0], [this.sortingOrder]);
        }

        return this.medis.torrents;
      },
      favoriteButtonClass() {
        return this.media.is_favored ? 'btn-outline-warning' : 'btn-warning';
      }
    },
    watch: {
      tracker() {
        this.init();
      },
    },
    async created() {
      if (this.tracker) {
        await this.init();
      }
    },
    methods: {
      async toggleFavorite() {
        if (this.media.is_favored) {
          this.media.is_favored = false;
          await removeFromFavorites(this.tracker.id, this.media.id);
        } else {
          this.media.is_favored = true;
          await addToFavorites(this.tracker.id, this.media.id);
        }
      },
      async init() {
        this.isLoading = true;

        let media;
        if (this.tracker.is_blocked) {
          media = await loadMediaBlocked(this.tracker.id, this.$route.params.mediaId);
        } else {
          media = await loadMedia(this.tracker.id, this.$route.params.mediaId);
        }

        this.media = media;

        this.isLoading = false;
      },
      handleDownload(torrent) {
        if (confirm(`Скачать "${torrent.name}"?`)) {
          startDownload(this.tracker, torrent.url, torrent.content_type);
          this.notifySuccess('Загрузка началась', torrent.name);
        }
      },
      switchSortingOrder() {
        this.sortingOrder = this.sortingOrder === 'asc' ? 'desc' : 'asc';
      },
    }
  }
</script>

<style scoped>

</style>
